version: "3"
services:
  postgres:
    container_name: postgres
    image: postgres:14.1
    ports:
      - 4321:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo_demo
